service: aws-executor-montage
app: aws-executor-cfo-montage

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  timeout: 900
  versionFunctions: false
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"       
      Resource: "arn:aws:s3:::hyperflow-montage/*"
      
    - Sid: AWSLambdaVPCAccessExecutionRole
      Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DeleteNetworkInterface
      Resource: "*"
    - Sid: AmazonElasticFileSystemClientFullAccess
      Effect: Allow
      Action:
        - elasticfilesystem:ClientMount
        - elasticfilesystem:ClientRootAccess
        - elasticfilesystem:ClientWrite
        - elasticfilesystem:DescribeMountTargets
      Resource: "*"


functions:

  aws-executor-2048:
    handler: handler.executor
    description: AWS executor 2048MB memory size
    memorySize: 2048
    events:
    - http:
        path: aws-executor-2048
        method: post
    fileSystemConfig:
      localMountPath: /mnt/montage
      arn: <placeholder>
    vpc:
      securityGroupIds:
        - sg-98c301df
      subnetIds:
        - <placeholder>
        - <placeholder>
        - <placeholder>
