service: aws-executor-ellipsoids
app: aws-executor-cfo-ellipsoids

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  timeout: 900
  versionFunctions: false
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
      Resource: "arn:aws:s3:::hyperflow-ellipsoids/*"

functions:

  aws-executor-128:
    handler: handler.executor
    description: AWS executor 128MB memory size
    memorySize: 128
    events:
    - http:
        path: aws-executor-128
        method: post

  aws-executor-256:
    handler: handler.executor
    description: AWS executor 256MB memory size
    memorySize: 256
    events:
    - http:
        path: aws-executor-256
        method: post

  aws-executor-512:
    handler: handler.executor
    description: AWS executor 512MB memory size
    memorySize: 512
    events:
    - http:
        path: aws-executor-512
        method: post
        
  aws-executor-768:
    handler: handler.executor
    description: AWS executor 768MB memory size
    memorySize: 768
    events:
    - http:
        path: aws-executor-768
        method: post
        
  aws-executor-1024:
    handler: handler.executor
    description: AWS executor 1024MB memory size
    memorySize: 1024
    events:
    - http:
        path: aws-executor-1024
        method: post

  aws-executor-1280:
    handler: handler.executor
    description: AWS executor 1280MB memory size
    memorySize: 1280
    events:
    - http:
        path: aws-executor-1280
        method: post
        
  aws-executor-1536:
    handler: handler.executor
    description: AWS executor 1536MB memory size
    memorySize: 1536
    events:
    - http:
        path: aws-executor-1536
        method: post
  
  aws-executor-1792:
    handler: handler.executor
    description: AWS executor 1792MB memory size
    memorySize: 1792
    events:
    - http:
        path: aws-executor-1792
        method: post

  aws-executor-2048:
      handler: handler.executor
      description: AWS executor 2048MB memory size
      memorySize: 2048
      events:
      - http:
          path: aws-executor-2048
          method: post
          
  aws-executor-2560:
    handler: handler.executor
    description: AWS executor 2560MB memory size
    memorySize: 2560
    events:
    - http:
        path: aws-executor-2560
        method: post

  aws-executor-3072:
    handler: handler.executor
    description: AWS executor 3072MB memory size
    memorySize: 3072
    events:
    - http:
        path: aws-executor-3072
        method: post
        
  aws-executor-4096:
    handler: handler.executor
    description: AWS executor 4096MB memory size
    memorySize: 4096
    events:
    - http:
        path: aws-executor-4096
        method: post
  
  aws-executor-5120:
    handler: handler.executor
    description: AWS executor 5120MB memory size
    memorySize: 5120
    events:
    - http:
        path: aws-executor-5120
        method: post

  aws-executor-6144:
      handler: handler.executor
      description: AWS executor 6144MB memory size
      memorySize: 6144
      events:
      - http:
          path: aws-executor-6144
          method: post
